"""Generate MicroHH case inputs (``.ini`` + ``<case>_input.nc``) from a config.

The MicroHH analogue of the FLEXPART options/RELEASES writers. Given a
:class:`~enforceflux.microhh.sim_config.MicroHHConfig`, it writes:

- ``<case_name>.ini`` — the namelist, and
- ``<case_name>_input.nc`` — the initial vertical profiles (this MicroHH reads
  a NetCDF init file with a ``z`` dimension and an ``init`` group, *not* a
  ``.prof`` text table).

The layout follows MicroHH's shipped ``cases/dispersion`` example: a passive
scalar released from a Gaussian blob in a dry convective boundary layer, driven
by a uniform mean wind with lateral inflow/outflow BCs so the plume advects
downwind (box +x). Nothing here needs the MicroHH binary.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from enforceflux.microhh.geometry import BoxProjection
from enforceflux.microhh.sim_config import MicroHHConfig


def _fmt_list(values: list[float]) -> str:
    return ",".join(f"{v:g}" for v in values)


def _projection(cfg: MicroHHConfig) -> BoxProjection:
    return BoxProjection(
        origin_lon=cfg.origin_lon,
        origin_lat=cfg.origin_lat,
        x_bearing_deg=cfg.x_bearing_deg,
        source_x0=cfg.source_x0,
        source_y0=cfg.source_y0,
    )


def build_ini(cfg: MicroHHConfig) -> str:
    """Return the ``.ini`` namelist text for the case."""
    proj = _projection(cfg)
    g = cfg.grid
    f = cfg.forcing
    name = cfg.scalar_name

    # Project sources and receptors into wind-aligned box metres.
    sx, sy, sz, sig_x, sig_y, sig_z = [], [], [], [], [], []
    for s in cfg.sources:
        x, y = proj.to_box(s.lon, s.lat)
        sx.append(x); sy.append(y); sz.append(s.alt_m)
        sig_x.append(s.sigma_x_m); sig_y.append(s.sigma_y_m); sig_z.append(s.sigma_z_m)

    col_x, col_y = [], []
    for r in cfg.receptors:
        x, y = proj.to_box(r.lon, r.lat)
        col_x.append(float(round(x))); col_y.append(float(round(y)))

    n_src = len(cfg.sources)
    total_time = cfg.spinup_s + cfg.runtime_s
    # Horizontal cross-section at source height; vertical slice through the
    # (first) source — gives 2D fields to render the plume.
    # An explicit plane wins: deriving it from sources[0] makes the slice an
    # accident of source ordering, which breaks run-to-run comparability.
    # Kept as floats: MicroHH snaps each plane to the nearest level itself, and
    # rounding to whole metres would collapse a 0.5 m beam height to 0.
    xy_level = float(cfg.cross_xy_m) if cfg.cross_xy_m is not None else (
        float(sz[0]) if sz else 0.5 * g.levels()[0])
    xz_slice = float(cfg.cross_xz_m) if cfg.cross_xz_m is not None else (
        float(sy[0]) if sy else 0.5 * g.ysize)

    lines: list[str] = []
    a = lines.append

    a(f"# MicroHH case '{cfg.case_name}' — generated by EnforceFlux")
    a(f"# scalar '{name}', {n_src} source(s), {len(cfg.receptors)} receptor(s)")
    _z = g.levels()
    if g.stretched:
        a(f"# grid {g.itot}x{g.jtot}x{g.ktot}  dx={g.dx:g} dy={g.dy:g} m, "
          f"stretched z: first level {_z[0]:.2f} m, top {_z[-1]:.0f} m, "
          f"growth {g.growth_ratio:.3f}")
    else:
        a(f"# grid {g.itot}x{g.jtot}x{g.ktot}  dx={g.dx:g} dy={g.dy:g} dz={g.dz:g} m")
    a("")

    # MPI decomposition: npx splits x and z, npy splits y (see decompose_workers).
    npx, npy = cfg.decomposition
    a("[master]")
    a(f"npx={npx}")
    a(f"npy={npy}")
    a("")

    a("[grid]")
    a(f"itot={g.itot}")
    a(f"jtot={g.jtot}")
    a(f"ktot={g.ktot}")
    a(f"xsize={g.xsize:g}")
    a(f"ysize={g.ysize:g}")
    a(f"zsize={g.zsize:g}")
    a("swspatialorder=2")
    a("")

    a("[advec]")
    a("swadvec=2i5")
    a("cflmax=1.3")
    a(f"fluxlimit_list={name}")
    a("")

    a("[diff]")
    a("swdiff=smag2")
    a("dnmax=0.3")
    a("")

    a("[thermo]")
    a("swthermo=dry")
    a("swbasestate=anelastic")
    a("pbot=100000.")
    a("")

    a("[force]")
    a("swlspres=0")
    a("swls=0")
    a("swwls=0")
    a("")

    a("[boundary]")
    a("swboundary=surface")
    a("mbcbot=noslip")
    a("mbctop=freeslip")
    a("sbcbot=flux")
    a("sbctop=neumann")
    a("sbot=0")
    a("stop=0")
    a(f"sbot[th]={f.surface_heat_flux_K_m_s:g}")
    a(f"stop[th]={f.thl_lapse_K_per_m:g}")
    a(f"z0m={f.z0m:g}")
    a(f"z0h={f.z0h:g}")
    # Lateral inflow/outflow so the plume leaves the domain downwind (+x = east
    # in box coords; wind blows from west inflow toward east outflow).
    if cfg.surface_flux_patches:
        # Reads <name>_bot_in.0000000 and imposes it as the per-cell surface
        # flux. This is what makes an area source a genuine SURFACE emitter
        # rather than a volumetric blob spread over the lowest model levels.
        a(f"sbot_2d_list={name}")
    a(f"scalar_outflow={name}")
    a("flow_direction[west]=inflow")
    a("flow_direction[east]=outflow")
    a("flow_direction[north]=outflow")
    a("flow_direction[south]=outflow")
    a("")

    a("[fields]")
    a("visc=1.e-5")
    a("svisc=1.e-5")
    a(f"slist={name}")
    a("rndseed=2")
    a("rndamp[th]=0.1")
    a("rndz=300.")
    a("rndexp=2.")
    a("")

    # strength [kg s-1] with swvmr=false is the *physical* mass emission rate:
    # MicroHH normalizes the Gaussian blob so ∫ρ(∂c/∂t)dV = strength exactly
    # (src/source.cxx calc_norm), independent of blob shape or grid. Scale by
    # cfg.emission_scale for unit-response (Jacobian) runs.
    strengths = [s.emission_rate_kg_s * cfg.emission_scale for s in cfg.sources]
    if n_src:
        a("[source]")
        a("swsource=1")
        a(f"sourcelist={','.join(name for _ in range(n_src))}")
        a(f"source_x0={_fmt_list(sx)}")
        a(f"source_y0={_fmt_list(sy)}")
        a(f"source_z0={_fmt_list(sz)}")
        a(f"sigma_x={_fmt_list(sig_x)}")
        a(f"sigma_y={_fmt_list(sig_y)}")
        a(f"sigma_z={_fmt_list(sig_z)}")
        a(f"strength={_fmt_list(strengths)}")
        a(f"swvmr={','.join('false' for _ in range(n_src))}")
        a("")

    a("[buffer]")
    a("swbuffer=1")
    a(f"zstart={0.75 * g.zsize:g}")
    a("sigma=0.00223")
    a("beta=2.")
    a("")

    a("[limiter]")
    a(f"limitlist={name}")
    a("")

    a("[time]")
    a("starttime=0")
    a(f"endtime={total_time}")
    a("dt=6.")                       # initial step; adaptivestep takes over
    a(f"dtmax={cfg.dt_max_s:g}")     # hard cap on the adaptive timestep
    a("savetime=3600")
    a("outputiter=50")
    a("adaptivestep=true")
    a("rkorder=4")
    a("")

    a("[stats]")
    a("swstats=1")
    a(f"sampletime={cfg.sampletime_s}")
    a("")

    a("[cross]")
    a("swcross=1")
    a(f"sampletime={cfg.sampletime_s}")
    a(f"crosslist={name},{name}_path")
    a(f"xy={xy_level:g}")
    a(f"xz={xz_slice:g}")
    a("")

    a("[column]")
    a("swcolumn=1")
    a(f"sampletime={cfg.sampletime_s}")
    a(f"coordinates[x]={_fmt_list(col_x)}")
    a(f"coordinates[y]={_fmt_list(col_y)}")
    a("")

    # Passthrough overrides: extra_ini = {section: {key: value}}
    for section, kv in cfg.extra_ini.items():
        a(f"[{section}]")
        for k, v in kv.items():
            a(f"{k}={v}")
        a("")

    return "\n".join(lines) + "\n"


def initial_profiles(cfg: MicroHHConfig) -> dict[str, np.ndarray]:
    """Compute the initial vertical profiles for the ``init`` group.

    Dry convective boundary layer: uniform mean wind along box +x, a well-mixed
    potential-temperature layer capped by an inversion at
    ``boundary_layer_height_m``, stable lapse rate aloft, and zero initial
    scalar. Mirrors ``cases/dispersion/dispersion_input.py``.
    """
    g = cfg.grid
    f = cfg.forcing
    z = g.levels()

    u = np.full_like(z, f.u_geo)
    v = np.full_like(z, f.v_geo)

    th = np.empty_like(z)
    h = f.boundary_layer_height_m
    th0 = f.thl_surface_K
    dth = f.inversion_strength_K
    dthz = f.inversion_depth_m
    lapse = f.thl_lapse_K_per_m
    for k, zk in enumerate(z):
        if zk <= h - 0.5 * dthz:
            th[k] = th0
        elif zk <= h + 0.5 * dthz:
            th[k] = th0 + dth / dthz * (zk - (h - 0.5 * dthz))
        else:
            th[k] = th0 + dth + lapse * (zk - (h + 0.5 * dthz))

    scalar = np.zeros_like(z)
    return {"z": z, "u": u, "v": v, "th": th, cfg.scalar_name: scalar}


def surface_flux_field(cfg: MicroHHConfig) -> np.ndarray:
    """Rasterise the surface-flux patches onto the box grid -> (jtot, itot).

    Returns the KINEMATIC flux, scalar-units x m/s, which is what MicroHH's
    ``sbcbot=flux`` boundary condition expects (the same convention as the
    kinematic heat flux in ``sbot[th]``). Dividing by a reference density is
    therefore required, not optional.

    Cells are assigned by testing each cell centre against the patch square in
    GEOGRAPHIC coordinates, so a box rotated to the wind samples the patch at
    its true orientation. Partial cells are all-or-nothing; with a 300 m patch
    on a 20 m grid that is a sub-percent effect on total emission, and
    :func:`write_case` reports the realised total so it can be checked.
    """
    from enforceflux.microhh.geometry import BoxProjection

    g = cfg.grid
    field = np.zeros((g.jtot, g.itot), dtype=np.float64)
    if not cfg.surface_flux_patches:
        return field

    proj = BoxProjection(
        origin_lon=cfg.origin_lon, origin_lat=cfg.origin_lat,
        x_bearing_deg=cfg.x_bearing_deg,
        source_x0=cfg.source_x0, source_y0=cfg.source_y0,
    )
    # Cell centres in box coords -> lon/lat -> geographic metres from origin.
    xb = (np.arange(g.itot) + 0.5) * g.dx
    yb = (np.arange(g.jtot) + 0.5) * g.dy
    xx, yy = np.meshgrid(xb, yb)
    lon, lat = proj.to_lonlat(xx, yy)

    rho = _reference_density(cfg)
    for patch in cfg.surface_flux_patches:
        m_per_deg_lat = 111_320.0
        m_per_deg_lon = m_per_deg_lat * np.cos(np.radians(patch.lat))
        east = (lon - patch.lon) * m_per_deg_lon
        north = (lat - patch.lat) * m_per_deg_lat
        half = patch.side_m / 2.0
        inside = (np.abs(east) <= half) & (np.abs(north) <= half)
        field[inside] += patch.flux_kg_m2_s / rho
    return field


def _reference_density(cfg: MicroHHConfig) -> float:
    """Near-surface air density from the case's own base state (kg m-3)."""
    R_D, P_BOT = 287.04, 100_000.0
    return P_BOT / (R_D * cfg.forcing.thl_surface_K)


def write_surface_flux_file(cfg: MicroHHConfig, path: Path) -> dict:
    """Write ``<scalar>_bot_in.0000000``: the 2-D bottom boundary condition.

    MicroHH reads this as a raw ``(jtot, itot)`` binary slice of the build's
    precision when ``[boundary] sbot_2d_list`` names the scalar.
    """
    field = surface_flux_field(cfg)
    field.astype(np.float64).tofile(path)

    rho = _reference_density(cfg)
    cell_area = cfg.grid.dx * cfg.grid.dy
    realised = float(field.sum() * rho * cell_area)      # kg/s back out
    intended = sum(p.emission_rate_kg_s for p in cfg.surface_flux_patches)
    return {
        "path": path, "cells": int((field > 0).sum()),
        "realised_kg_s": realised, "intended_kg_s": intended,
        "rho": rho,
    }


def write_input_nc(cfg: MicroHHConfig, path: Path) -> Path:
    """Write ``<case>_input.nc`` (dim ``z`` + ``init`` group) via netCDF4."""
    import netCDF4 as nc

    prof = initial_profiles(cfg)
    z = prof["z"]
    ds = nc.Dataset(path, mode="w", datamodel="NETCDF4", clobber=True)
    try:
        ds.createDimension("z", z.size)
        ds.createVariable("z", "f8", ("z",))[:] = z

        init = ds.createGroup("init")
        for var in ("u", "v", "th", cfg.scalar_name):
            init.createVariable(var, "f8", ("z",))[:] = prof[var]
        # Inflow profile for the non-periodic (outflow) scalar.
        init.createVariable(f"{cfg.scalar_name}_inflow", "f8", ("z",))[:] = prof[cfg.scalar_name]
    finally:
        ds.close()
    return path


def write_case(cfg: MicroHHConfig) -> dict[str, Path]:
    """Write ``.ini`` and ``<case>_input.nc`` into ``cfg.case_dir``."""
    cfg.case_dir.mkdir(parents=True, exist_ok=True)
    ini_path = cfg.case_dir / f"{cfg.case_name}.ini"
    nc_path = cfg.case_dir / f"{cfg.case_name}_input.nc"
    ini_path.write_text(build_ini(cfg))
    write_input_nc(cfg, nc_path)
    out = {"ini": ini_path, "input_nc": nc_path}

    if cfg.surface_flux_patches:
        bot_path = cfg.case_dir / f"{cfg.scalar_name}_bot_in.0000000"
        info = write_surface_flux_file(cfg, bot_path)
        out["surface_flux"] = bot_path
        # Rasterising a rotated square onto a Cartesian grid is all-or-nothing
        # per cell, so verify the realised emission before trusting the run.
        drift = abs(info["realised_kg_s"] / info["intended_kg_s"] - 1.0)
        if drift > 0.05:
            raise ValueError(
                f"Surface-flux raster realises {info['realised_kg_s']:.4e} kg/s "
                f"but the patches specify {info['intended_kg_s']:.4e} kg/s "
                f"({100*drift:.1f}% off). The patch is probably too small for "
                f"dx={cfg.grid.dx:g} m, or falls outside the box."
            )
    return out
