"""Generate MicroHH case inputs (``.ini`` + ``<case>_input.nc``) from a config.

The MicroHH analogue of the FLEXPART options/RELEASES writers. Given a
:class:`~enforceflux.microhh.sim_config.MicroHHConfig`, it writes:

- ``<case_name>.ini`` — the namelist, and
- ``<case_name>_input.nc`` — the initial vertical profiles (this MicroHH reads
  a NetCDF init file with a ``z`` dimension and an ``init`` group, *not* a
  ``.prof`` text table).

The layout follows MicroHH's shipped ``cases/dispersion`` example: a passive
scalar released from a Gaussian blob in a dry convective boundary layer, driven
by a uniform mean wind with lateral inflow/outflow BCs so the plume advects
downwind (box +x). Nothing here needs the MicroHH binary.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from enforceflux.microhh.geometry import BoxProjection
from enforceflux.microhh.sim_config import MicroHHConfig


def _fmt_list(values: list[float]) -> str:
    return ",".join(f"{v:g}" for v in values)


def _projection(cfg: MicroHHConfig) -> BoxProjection:
    return BoxProjection(
        origin_lon=cfg.origin_lon,
        origin_lat=cfg.origin_lat,
        x_bearing_deg=cfg.x_bearing_deg,
        source_x0=cfg.source_x0,
        source_y0=cfg.source_y0,
    )


def build_ini(cfg: MicroHHConfig) -> str:
    """Return the ``.ini`` namelist text for the case."""
    proj = _projection(cfg)
    g = cfg.grid
    f = cfg.forcing
    name = cfg.scalar_name
    # Scalars transported by MicroHH. The first is the emitted source scalar;
    # any others (H2O today) are passive tracers with only an initial profile.
    scalar_list = [name] + ([cfg.h2o_name] if cfg.include_h2o else [])

    # Project geographic points from the private native YAML into box metres.
    sx, sy, sz, sig_x, sig_y, sig_z = [], [], [], [], [], []
    for s in cfg.sources:
        x, y = proj.to_box(s.lon, s.lat)
        sx.append(x); sy.append(y); sz.append(s.alt_m)
        sig_x.append(s.sigma_x_m); sig_y.append(s.sigma_y_m); sig_z.append(s.sigma_z_m)

    col_x, col_y = [], []
    for r in cfg.receptors:
        x, y = proj.to_box(r.lon, r.lat)
        col_x.append(float(round(x))); col_y.append(float(round(y)))

    n_src = len(cfg.sources)
    start_time = cfg.restart_time_s or 0
    total_time = start_time + cfg.spinup_s + cfg.runtime_s
    # Horizontal cross-section at source height; vertical slice through the
    # (first) source — gives 2D fields to render the plume.
    # An explicit plane wins: deriving it from sources[0] makes the slice an
    # accident of source ordering, which breaks run-to-run comparability.
    # Kept as floats: MicroHH snaps each plane to the nearest level itself, and
    # rounding to whole metres would collapse a 0.5 m beam height to 0.
    xy_level = float(cfg.cross_xy_m) if cfg.cross_xy_m is not None else (
        float(sz[0]) if sz else 0.5 * g.levels()[0])
    xz_slice = float(cfg.cross_xz_m) if cfg.cross_xz_m is not None else (
        float(sy[0]) if sy else 0.5 * g.ysize)

    lines: list[str] = []
    a = lines.append

    a(f"# MicroHH case '{cfg.case_name}' — generated by EnforceFlux")
    a(f"# scalar '{name}', {n_src} source(s), {len(cfg.receptors)} receptor(s)")
    _z = g.levels()
    if g.stretched:
        a(f"# grid {g.itot}x{g.jtot}x{g.ktot}  dx={g.dx:g} dy={g.dy:g} m, "
          f"stretched z: first level {_z[0]:.2f} m, top {_z[-1]:.0f} m, "
          f"growth {g.growth_ratio:.3f}")
    else:
        a(f"# grid {g.itot}x{g.jtot}x{g.ktot}  dx={g.dx:g} dy={g.dy:g} dz={g.dz:g} m")
    a("")

    # MPI decomposition: npx splits x and z, npy splits y (see decompose_workers).
    npx, npy = cfg.decomposition
    a("[master]")
    a(f"npx={npx}")
    a(f"npy={npy}")
    a("")

    a("[grid]")
    a(f"itot={g.itot}")
    a(f"jtot={g.jtot}")
    a(f"ktot={g.ktot}")
    a(f"xsize={g.xsize:g}")
    a(f"ysize={g.ysize:g}")
    a(f"zsize={g.zsize:g}")
    a("swspatialorder=2")
    a("")

    a("[advec]")
    a("swadvec=2i5")
    a("cflmax=1.3")
    a(f"fluxlimit_list={','.join(scalar_list)}")
    a("")

    a("[diff]")
    a("swdiff=smag2")
    a("dnmax=0.3")
    a("")

    a("[thermo]")
    a("swthermo=dry")
    a("swbasestate=anelastic")
    a("pbot=100000.")
    a("")

    a("[force]")
    a("swlspres=0")
    a("swls=0")
    a("swwls=0")
    a("")

    a("[boundary]")
    a("swboundary=surface")
    a("mbcbot=noslip")
    a("mbctop=freeslip")
    a("sbcbot=flux")
    a("sbctop=neumann")
    a("sbot=0")
    a("stop=0")
    a(f"sbot[th]={f.surface_heat_flux_K_m_s:g}")
    a(f"stop[th]={f.thl_lapse_K_per_m:g}")
    a(f"z0m={f.z0m:g}")
    a(f"z0h={f.z0h:g}")
    # Lateral inflow/outflow so the plume leaves the domain downwind (+x = east
    # in box coords; wind blows from west inflow toward east outflow).
    if cfg.surface_flux_patches:
        # Reads <name>_bot_in.0000000 and imposes it as the per-cell surface
        # flux. This is what makes an area source a genuine SURFACE emitter
        # rather than a volumetric blob spread over the lowest model levels.
        a(f"sbot_2d_list={name}")
    # H2O has no surface flux in this configuration — passive tracer only.
    a(f"scalar_outflow={','.join(scalar_list)}")
    a("flow_direction[west]=inflow")
    a("flow_direction[east]=outflow")
    a("flow_direction[north]=outflow")
    a("flow_direction[south]=outflow")
    a("")

    a("[fields]")
    a("visc=1.e-5")
    a("svisc=1.e-5")
    a(f"slist={','.join(scalar_list)}")
    a("rndseed=2")
    a("rndamp[th]=0.1")
    a("rndz=300.")
    a("rndexp=2.")
    a("")

    # strength [kg s-1] with swvmr=false is the *physical* mass emission rate:
    # MicroHH normalizes the Gaussian blob so ∫ρ(∂c/∂t)dV = strength exactly
    # (src/source.cxx calc_norm), independent of blob shape or grid. Scale by
    # cfg.emission_scale for unit-response (Jacobian) runs.
    strengths = [s.emission_rate_kg_s * cfg.emission_scale for s in cfg.sources]
    if n_src:
        a("[source]")
        a("swsource=1")
        a(f"sourcelist={','.join(name for _ in range(n_src))}")
        a(f"source_x0={_fmt_list(sx)}")
        a(f"source_y0={_fmt_list(sy)}")
        a(f"source_z0={_fmt_list(sz)}")
        a(f"sigma_x={_fmt_list(sig_x)}")
        a(f"sigma_y={_fmt_list(sig_y)}")
        a(f"sigma_z={_fmt_list(sig_z)}")
        a(f"strength={_fmt_list(strengths)}")
        a(f"swvmr={','.join('false' for _ in range(n_src))}")
        a("")

    a("[buffer]")
    a("swbuffer=1")
    a(f"zstart={0.75 * g.zsize:g}")
    a("sigma=0.00223")
    a("beta=2.")
    a("")

    a("[limiter]")
    a(f"limitlist={','.join(scalar_list)}")
    a("")

    a("[time]")
    a(f"starttime={start_time}")
    a(f"endtime={total_time}")
    a("dt=6.")                       # initial step; adaptivestep takes over
    a(f"dtmax={cfg.dt_max_s:g}")     # hard cap on the adaptive timestep
    a("savetime=3600")
    a("outputiter=50")
    a("adaptivestep=true")
    a("rkorder=4")
    a("")

    a("[stats]")
    a("swstats=1")
    a(f"sampletime={cfg.stats_sampletime_s or cfg.sampletime_s:g}")
    a("")

    a("[cross]")
    a("swcross=1")
    a(f"sampletime={cfg.cross_sampletime_s or cfg.sampletime_s:g}")
    a(f"crosslist={name},{name}_path")
    a(f"xy={xy_level:g}")
    a(f"xz={xz_slice:g}")
    a("")

    a("[column]")
    a("swcolumn=1")
    a(f"sampletime={cfg.column_sampletime_s or cfg.sampletime_s:g}")
    a(f"coordinates[x]={_fmt_list(col_x)}")
    a(f"coordinates[y]={_fmt_list(col_y)}")
    a("")

    # Passthrough overrides: extra_ini = {section: {key: value}}
    for section, kv in cfg.extra_ini.items():
        a(f"[{section}]")
        for k, v in kv.items():
            a(f"{k}={v}")
        a("")

    return "\n".join(lines) + "\n"


def initial_profiles(cfg: MicroHHConfig) -> dict[str, np.ndarray]:
    """Compute the initial vertical profiles for the ``init`` group.

    Dry convective boundary layer: uniform mean wind along box +x, a well-mixed
    potential-temperature layer capped by an inversion at
    ``boundary_layer_height_m``, stable lapse rate aloft, and zero initial
    scalar. Mirrors ``cases/dispersion/dispersion_input.py``.
    """
    g = cfg.grid
    f = cfg.forcing
    z = g.levels()

    u = np.full_like(z, f.u_geo)
    v = np.full_like(z, f.v_geo)

    th = np.empty_like(z)
    h = f.boundary_layer_height_m
    th0 = f.thl_surface_K
    dth = f.inversion_strength_K
    dthz = f.inversion_depth_m
    lapse = f.thl_lapse_K_per_m
    for k, zk in enumerate(z):
        if zk <= h - 0.5 * dthz:
            th[k] = th0
        elif zk <= h + 0.5 * dthz:
            th[k] = th0 + dth / dthz * (zk - (h - 0.5 * dthz))
        else:
            th[k] = th0 + dth + lapse * (zk - (h + 0.5 * dthz))

    scalar = np.zeros_like(z)
    prof = {"z": z, "u": u, "v": v, "th": th, cfg.scalar_name: scalar}
    if cfg.include_h2o:
        # Simple exponential-decay tropospheric moisture profile [kg/kg].
        prof[cfg.h2o_name] = cfg.h2o_surface_kg_kg * np.exp(-z / cfg.h2o_scale_height_m)
    return prof


def surface_flux_field(cfg: MicroHHConfig) -> np.ndarray:
    """Rasterise the surface-flux patches onto the box grid -> (jtot, itot).

    Returns the KINEMATIC flux, scalar-units x m/s, which is what MicroHH's
    ``sbcbot=flux`` boundary condition expects (the same convention as the
    kinematic heat flux in ``sbot[th]``). Dividing by a reference density is
    therefore required, not optional.

    Cells are assigned by testing each cell centre against the patch square in
    GEOGRAPHIC coordinates, so a box rotated to the wind samples the patch at
    its true orientation. Partial cells are all-or-nothing; with a 300 m patch
    on a 20 m grid that is a sub-percent effect on total emission, and
    :func:`write_case` reports the realised total so it can be checked.
    """
    from enforceflux.microhh.geometry import BoxProjection

    g = cfg.grid
    field = np.zeros((g.jtot, g.itot), dtype=np.float64)
    if not cfg.surface_flux_patches:
        return field

    proj = BoxProjection(
        origin_lon=cfg.origin_lon, origin_lat=cfg.origin_lat,
        x_bearing_deg=cfg.x_bearing_deg,
        source_x0=cfg.source_x0, source_y0=cfg.source_y0,
    )
    rho = _reference_density(cfg)

    def clip(poly, axis, bound, keep_greater):
        """Sutherland-Hodgman clip against one axis-aligned half-plane."""
        if not poly:
            return []
        out = []
        for start, end in zip(poly, poly[1:] + poly[:1]):
            sv, ev = start[axis], end[axis]
            sin = sv >= bound if keep_greater else sv <= bound
            ein = ev >= bound if keep_greater else ev <= bound
            if sin != ein:
                frac = (bound - sv) / (ev - sv)
                cross = [start[0] + frac * (end[0] - start[0]),
                         start[1] + frac * (end[1] - start[1])]
                out.append(cross)
            if ein:
                out.append(end)
        return out

    def overlap_area(poly, x0, x1, y0, y1):
        clipped = clip(poly, 0, x0, True)
        clipped = clip(clipped, 0, x1, False)
        clipped = clip(clipped, 1, y0, True)
        clipped = clip(clipped, 1, y1, False)
        if len(clipped) < 3:
            return 0.0
        x = np.asarray([p[0] for p in clipped])
        y = np.asarray([p[1] for p in clipped])
        return 0.5 * abs(float(np.dot(x, np.roll(y, -1)) -
                               np.dot(y, np.roll(x, -1))))

    # Integrate the true overlap of each geographic source square with every
    # native LES cell.  Centre-in-cell rasterisation drops 40 m truth cells on
    # an 80 m LES grid and can materially change both total Q and its spatial
    # pattern.  Fractional overlap conserves mass, including for rotated boxes.
    bearing = np.radians(cfg.x_bearing_deg)
    sin_b, cos_b = np.sin(bearing), np.cos(bearing)
    cell_area = g.dx * g.dy
    for patch in cfg.surface_flux_patches:
        cx, cy = proj.to_box(patch.lon, patch.lat)
        half = patch.side_m / 2.0
        poly = []
        for east, north in ((-half, -half), (half, -half),
                            (half, half), (-half, half)):
            poly.append([
                cx + east * sin_b + north * cos_b,
                cy - east * cos_b + north * sin_b,
            ])
        xs = [p[0] for p in poly]
        ys = [p[1] for p in poly]
        i0 = max(0, int(np.floor(min(xs) / g.dx)))
        i1 = min(g.itot - 1, int(np.floor(max(xs) / g.dx)))
        j0 = max(0, int(np.floor(min(ys) / g.dy)))
        j1 = min(g.jtot - 1, int(np.floor(max(ys) / g.dy)))
        for j in range(j0, j1 + 1):
            for i in range(i0, i1 + 1):
                area = overlap_area(
                    poly, i * g.dx, (i + 1) * g.dx,
                    j * g.dy, (j + 1) * g.dy,
                )
                field[j, i] += patch.flux_kg_m2_s * area / (rho * cell_area)
    return field


def _reference_density(cfg: MicroHHConfig) -> float:
    """Near-surface air density from the case's own base state (kg m-3)."""
    R_D, P_BOT = 287.04, 100_000.0
    return P_BOT / (R_D * cfg.forcing.thl_surface_K)


def write_surface_flux_file(cfg: MicroHHConfig, path: Path) -> dict:
    """Write ``<scalar>_bot_in.0000000``: the 2-D bottom boundary condition.

    MicroHH reads this as a raw ``(jtot, itot)`` binary slice of the build's
    precision when ``[boundary] sbot_2d_list`` names the scalar.
    """
    field = surface_flux_field(cfg)
    dtype = np.float32 if cfg.precision == "float32" else np.float64
    field.astype(dtype).tofile(path)

    rho = _reference_density(cfg)
    cell_area = cfg.grid.dx * cfg.grid.dy
    realised = float(field.sum() * rho * cell_area)      # kg/s back out
    intended = sum(p.emission_rate_kg_s for p in cfg.surface_flux_patches)
    return {
        "path": path, "cells": int((field > 0).sum()),
        "realised_kg_s": realised, "intended_kg_s": intended,
        "rho": rho,
    }


def write_input_nc(cfg: MicroHHConfig, path: Path) -> Path:
    """Write ``<case>_input.nc`` (dim ``z`` + ``init`` group) via netCDF4."""
    import netCDF4 as nc

    prof = initial_profiles(cfg)
    z = prof["z"]
    ds = nc.Dataset(path, mode="w", datamodel="NETCDF4", clobber=True)
    try:
        ds.createDimension("z", z.size)
        ds.createVariable("z", "f8", ("z",))[:] = z

        init = ds.createGroup("init")
        scalar_vars = [cfg.scalar_name] + ([cfg.h2o_name] if cfg.include_h2o else [])
        for var in ("u", "v", "th", *scalar_vars):
            init.createVariable(var, "f8", ("z",))[:] = prof[var]
        # Inflow profile for the non-periodic (outflow) scalars.
        for sv in scalar_vars:
            init.createVariable(f"{sv}_inflow", "f8", ("z",))[:] = prof[sv]
    finally:
        ds.close()
    return path


def write_case(cfg: MicroHHConfig) -> dict[str, Path]:
    """Write ``.ini`` and ``<case>_input.nc`` into ``cfg.case_dir``."""
    cfg.case_dir.mkdir(parents=True, exist_ok=True)
    ini_path = cfg.case_dir / f"{cfg.case_name}.ini"
    nc_path = cfg.case_dir / f"{cfg.case_name}_input.nc"
    ini_path.write_text(build_ini(cfg))
    write_input_nc(cfg, nc_path)
    out = {"ini": ini_path, "input_nc": nc_path}

    if cfg.surface_flux_patches:
        bot_path = cfg.case_dir / f"{cfg.scalar_name}_bot_in.0000000"
        info = write_surface_flux_file(cfg, bot_path)
        out["surface_flux"] = bot_path
        # Rasterising a rotated square onto a Cartesian grid is all-or-nothing
        # per cell, so verify the realised emission before trusting the run.
        drift = abs(info["realised_kg_s"] / info["intended_kg_s"] - 1.0)
        if drift > 0.05:
            raise ValueError(
                f"Surface-flux raster realises {info['realised_kg_s']:.4e} kg/s "
                f"but the patches specify {info['intended_kg_s']:.4e} kg/s "
                f"({100*drift:.1f}% off). The patch is probably too small for "
                f"dx={cfg.grid.dx:g} m, or falls outside the box."
            )
    return out
